# Generated by Django 4.2.16 on 2024-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('1', '0-1.5'), ('2', '1.5-3'), ('3', '3-5'), ('4', '5-7'), ('5', '7-10')], default='1', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateField(verbose_name='Activity Date')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
