# Generated by Django 4.2.16 on 2024-09-25 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
